### ISSUE TITLE
Where is the 'data' folder?

### ISSUE THREAD

**Issue by LittleBrainz** [thsant/scipy4cv#1]
Let me first say that I have found the tutorials to be extremely useful. Thank you!

However, the code within the Jupyter notebooks refer to an assortment of sample files in the 'data' folder, but that folder is not in the repo.

Are you able to include the sample files with this repo?

Kind regards,

Stephen

**Comment by thsant** [comment]
Stephen,

I added the data folder, you can 'pull' it now. See the README.md in the data folder for instructions about getting CAVIAR and Middleburry data.

Best Regards

Thiago
